version: 2

project_name: scaf

before:
  hooks:
    - go mod tidy

builds:
  - id: scaf
    main: ./cmd/scaf
    binary: scaf
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/PrimCraft/scaf/internal/cmd.Version={{.Version}}
      - -X github.com/PrimCraft/scaf/internal/cmd.Commit={{.Commit}}
      - -X github.com/PrimCraft/scaf/internal/cmd.Date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: PrimCraft
    name: scaf
  # auto: tags like v1.0.0-beta.1 or v1.0.0-rc1 become prereleases
  prerelease: auto
  # Only mark stable releases as "latest"
  make_latest: "{{ not .Prerelease }}"
  draft: false
